services:
  neo4j-test:
    image: neo4j:5.26.2
    ports:
      - "7475:7474" # HTTP
      - "7688:7687" # Bolt
    volumes:
      - neo4j_test_data:/data
    environment:
      - NEO4J_AUTH=neo4j/test_password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  neo4j_test_data: